services:
  hdtracker:
    image: ghcr.io/dvnkln/hdtracker:latest
    # Remove the next line to only use the published image instead of building locally
    build: .
    container_name: hdtracker
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file: .env
    volumes:
      - hdtracker-data:/data

volumes:
  hdtracker-data:
