import { resolve } from 'node:path';

// Where all persistent data lives. In Docker this is /data (set in the Dockerfile).
export const DATA_DIR = resolve(process.env.DATA_DIR ?? './data');

export const DB_PATH = resolve(DATA_DIR, 'hdtracker.db');

// SQL migration files generated by drizzle-kit (npm run db:generate).
export const MIGRATIONS_DIR = resolve(process.env.MIGRATIONS_DIR ?? './drizzle');
